services:
    traefik:
        image: traefik:v3.0
        container_name: traefik
        command:
            - "--providers.docker=true"
            - "--providers.file.directory=/etc/traefik/dynamic"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./dev/traefik.yaml:/etc/traefik/dynamic/traefik.yaml"
            - "./tmp/certs:/certs"
    whoami:
        image: traefik/whoami
        container_name: whoami
        extra_hosts:
            - "host.docker.internal:host-gateway"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`echo.tale.test`)"
            - "traefik.http.routers.whoami.entrypoints=websecure"
            - "traefik.http.routers.whoami.tls=true"
            - "traefik.http.middlewares.forward-auth.forwardauth.address=http://host.docker.internal:4180"
            - "traefik.http.routers.whoami.middlewares=forward-auth"
    mafl:
        image: hywax/mafl:latest
        container_name: mafl
        volumes:
            - "./dev/mafl.yaml:/app/data/config.yml"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mafl.rule=Host(`mafl.tale.test`)"
            - "traefik.http.routers.mafl.entrypoints=websecure"
            - "traefik.http.routers.mafl.tls=true"
            - "traefik.http.routers.mafl.middlewares=forward-auth"
